[package]
name = "rust"
version = "0.0.1"
authors = ["Wolfgang Vitzthum <>"]
edition = "2021"

[[bin]]
name = "http"
path = "./src/http.rs"

[dependencies]
rug = "1.9.0"
warp = "0.2.3"
tokio = {version = "0.2.21", features=["full"]}
