[package]
name = "rust"
version = "0.1.0"
authors = ["Wolfgang Vitzthum"]
edition = "2021"

[[bin]]
name = "kafka"
path = "./src/kafka.rs"

[dependencies]
rdkafka = { version = "0.25", features = ["cmake-build"] }